README.md
sift.js
test/basic-test.js

Thank you for this module, just what I was looking for!
I would like to add a `indexOf` function to Sift, similar to `Array.prototype.indexOf`.
I.e. it returns a 0-based index for the first matching element and `-1` if not found.
Example usage:
```javascript
var persons = [{name: 'Jane Doe', age: 26}, {name: 'Janet Fonda', age: 38}];
sift.indexOf({age: {$gt: 30}}, persons); // = 1
sift.indexOf({age: {$gt: 40}}, persons); // = -1
```
What do you think?

Add indexOf to get index of first matching element in target

---

sift.js

I attempted to use sift in a project where we use a customized REPL and encountered an issue where things didn't filter properly. All of the examples were returning an empty array instead of the expected values. The problem turned out to be the way the statement was being checked to see if it was an Object. I snagged the `isObject` code from `lodash` and used that for the check instead and the issue goes away. The issue can be observed for yourself by creating any custom REPL environment. The following would do:
```javascript
require('repl').start({prompt: 'custom> '})
```
Then using it:
```
$ node custom-repl.js
custom> var sift = require('sift');
undefined
custom> sift({ $in: ['hello','world'] }, ['hello','sifted','array!']);
[]
custom> 
```

Add an isObject function and use it.

---

sift.js
test/operations-test.js

This is quite "ticky-tack" but in the spirit of this awesome library performing the same as MongoDB, below is a difference I've found.
Say I have the document in MongoDB:
{"age":29}
This query returns this document (in Mongo)
{"age":{$gt:0}}
This query fails to return the document (in Mongo)
{"age":{$gt:null}}
Both queries return the document in sift when the query of "null" should not return anything.  Below is an actual code example:
`sift({"age":{$gt:null}}, [{"age":29}])`
Expected result: []
Actual result: [{"age":29}]

Typesafe $gt, $lt, $gte, and $lte comparisons to match MongoDB spec.

---

sift.js

Safari & Firefox have a different result for the constructor.toString() method than Chrome/v8.  Specifically it has a few extra spaces/newlines.  This change makes the comparison support both types.  Seems to be working fine in Safari/FF after this modification.

fix #75: cross-browser support

---

README.md
sift.js
test/operations-test.js

This is an attempt to closes #69.
I added `$options` which is only passed to `$regex` to set the regex options (i.e. `i`).
```js
sift({ $regex: "^f", $options: "i", $nin: ["frank"] }, ["frank", "fred", "sam", "frost"]); // ["fred", "frost"]
```
I'm happy to update this according to your input.
Thanks

adds $options for $regex

---

sift.js
test/objects-test.js
test/operations-test.js

If a given array of items with different attributes is given, `sift` returns the matched items and
the items with the missing attribute.
```js
var persons = [{
id: 1,
prof: 'Mr. Moriarty'
}, {
id: 2,
prof: 'Mycroft Holmes'
}, {
id: 3,
name: 'Dr. Watson',
prof: 'Doctor'
}, {
id: 4,
name: 'Mr. Holmes',
prof: 'Detective'
}];
var q = { "name": { "$regex": "n" } };
var sifted = sift(q, persons);
// Expected =>
// [ { id: 3, name: 'Dr. Watson', prof: 'Doctor' } ]
// Actual =>
// [ { id: 1, prof: 'Mr. Moriarty' },
//   { id: 2, prof: 'Mycroft Holmes' },
//   { id: 3, name: 'Dr. Watson', prof: 'Doctor' } ]
```
This fixes this issue:
```js
$regex: function(a, b) {
return b && a.test(b); // <= check if b is something
}
```

don't test undefined values in $regex

---

sift.js

The current implementation of `$options` modifies the original `query`. This is in some cases not good.
I change it to just skip it in the for loop.
Sorry for the inconvenience, since I introduced `$options` my self :frowning: .

the original query should not be modified

---

.travis.yml
package.json

When I do `npm test` in my local machine, it fails because it tries to send Coveralls reports.
This makes `npm test` work in development, yet still run Coveralls reports in TravisCI.

Only run coveralls tests in Travis

---

sift.js
test/use-test.js

The inability to compare on custom objects is a show-stopper for me. The most obvious use case is an `ObjectID` (i.e. #47) but also applies to any custom object you may choose to have in an array.
I churned many ideas over how to solve this issue without a bunch of changes and I think I've found a fair solution. It introduces `sift.compare(a,b)` as an overridable function that is called for `$eq`,`$ne`,`$gt`,`$gte`,`$lt`, and `$lte`. The default implementation, when invoked, will return `-1`,`0`,`1` or `undefined` to indicate `<`,`===`,`>`, and `not applicable`.
Developers that choose to overwrite the `compare` function can add additional comparison checks as desired for their custom objects. This could be as simple as calling `.valueOf()` or `.toString()` on the object before handing it …

customizable `compare` function

---

README.md
package.json
sift.js
test/immutable-test.js

How do you feel about adding support for [`Immutable.js`][i]?
I created this POC that it would work, if you like it I can add more tests and documentation.
It would be great to see this feature in sift.
We currently do `Immutable.fromJS(list.toJS().filter(sift(query)));` which is extremely slow (because of the convertion from and to js).
The only thing I changed is how values are accessed on objects/arrays.
[i]: http://facebook.github.io/immutable-js/

adds support for immutable datastructures

---

sift.js

Seems it makes sense to keep ES5 compatibility. If not - lets please bump major version. Currently one of our builds is failing as it still uses node 0.0.10. Thanks!

ES5 compatilbility

---

index.d.ts

there is a difference between default export and what sift uses. the d.ts as it was did not describe the way sift should be imported in runtime.
the difference (in typescript) is between:
```
import sift from 'sift'; // the wrong way. does not work in runtime, but fits the d.ts before the fix
import sift = require('sift'); // the way sift actually works. works in runtime but fails validation with the pre-fix d.ts
```

fix bug in d.ts

---

sift.js
test/operations-test.js

The following query: {"a.b": {$exists: true, $nin: [null]}} would also return results where "a.b" is undefined. Using $exists alone, or the $nin alone would behave as expected (not returning such documents). Only when combining the two does the issue reproduce.
Traced this to a bug in $and. Removed the problematic lines in $and, and added UT for our use case.

$and on undefined element

---

sift.js
test/operations-test.js

This actually adds support for ObjectId equalities.
Fixes #133 
Also did few minor optimizations:
* `$nor` -> not `$or`
* simplified `isVanillaObject` implementation
* utilized existing functions instead of `instanceof`
* renamed `operator` to `OPERATORS`

feat(tojson): adds check for toJSON method in comparable

---

index.d.ts

Fixes these TypeScript compilation errors in newer versions of TypeScript. Please merge asap @crcn, this will break everyone's TypeScript builds.
```
node_modules/sift/index.d.ts(22,54): error TS2344: Type 'T[0][index]' does not satisfy the constraint 'any[]'.
node_modules/sift/index.d.ts(32,35): error TS2344: Type 'T[0][P]' does not satisfy the constraint 'any[]'.
```

fix(typescript): Fixes typescript compilation issues.

---

sift.js
test/objects-test.js

Addresses issue #143  
If running a $ne operation on an array of sub-objects, the object being filtered should only pass if all of the sub-objects pass the $ne query.  Prior to this the object would pass if only one of the sub-objects passed the $ne query.

Bring to mongo spec for $ne on fields of arrays of objects.

---

sift.js
test/basic-test.js

Call comparable on both sides, so that the correct logic is followed
when filtering with $eq or $ne. 
The test cases take advantage of the `toJSON` feature in `comparable` to demonstrate the fixed behavior.

Fix $eq & $ne to work with complex objects

---

src/index.js

This change makes `src/index.js` compatible with IE11 again.
It seems that Babel is not used during the build process for `sift.min.js`, so the lib source in `src/index.js` must use only the syntax that is supported by all target browsers. IE 11 does not support shorthand property definitions, so we have to write the long-form in every case.

IE11 compat

---

.travis.yml
index.d.ts
tsconfig.json

1. Generate d.ts files for all .js files by adding `"declaration": true` in tsconfig.json.
2. In index.d.ts, export * from './lib/core' instead of './core'
Fixes #173

Fix d.ts generation

---

src/core.ts

All of the optional properties in `Query` admit `undefined` under the TS `strict` flag (which includes `strictNullChecks`), which isn't compatible with the index signature, causing an error to be issued. Explicitly including `undefined` in the index signature fixes the issue.

Make the sift public API compile under `strict`

---

package.json
src/core.ts
src/index.ts
src/operations.ts
test/types.ts

Fixes #197. Here's the updated TypeScript API:
```typescript
type Person = {
name: string,
last: string
};
const filter = sift<Person>({ name: "john", last: { $eq: "square" }});
```

Generic query types

---

package.json
src/core.ts
src/index.ts
src/operations.ts
test/operations-test.js
test/types.js
test/types.ts

Fixes #202 
Notes:
- Exposes operations instances
- Operations now have a `name` prop that includes `$in`, `$eq`, `$lt`, etc.
Demo:
```typescript
import {createDefaultQueryOperation, createOperationTester} from "sift";
type Item = { name: string };
const operation = createDefaultQueryOperation<Item>({ name: /\w+/ });
const test = createOperationTester(operation);
test({ name: "blah" });
```
Lmk what you think of this @stalniy!

Expose operation creator

---

src/core.ts

From the MongoDB documentation and the actual code, the document can be either `this` or an argument (`obj` for staying close to the documentation).
This change adds the missing `obj` argument.

fix(types): $where signature

---

package-lock.json
package.json
src/core.ts
src/operations.ts
test/basic-test.js

No API change here, just removing the check for $ and keying off registered operations instead. As a result, this works:
```javascript
createQueryTester({ eq: 5 }, { operations: { eq: $eq }));
```

Custom ops no $

---

src/core.ts
src/utils.ts
test/objects-test.js

Issue:
Trying to query for a valid property on an array-like object fails, because `walkKeyPathValues` only checks if indices (properties) are numbers before iterating over the array.
See test case [here](https://github.com/crcn/sift.js/pull/267/files#diff-e844130e83ca2f7ba42dc5365236208087b960bbd84d85497293648647422835R287)
Fix:
When encoutering arrays, also check if the property exists (and that it's not a method, e.g. `.map()`, `.at()`)

fix: property access in array-like
